### ISSUE TITLE
[Feature Request] Option to choose default gallery app

### ISSUE THREAD

**Issue by asisnil** [Xposed-Modules-Repo/com.luckyzyx.luckytool#11]
It would be great if we could open google photos instead of default gallery when clicking this.

![Screenshot_2024-02-17-09-34-13-18_d1e180874abfbe4d796ce10558f8141a](https://github.com/Xposed-Modules-Repo/com.luckyzyx.luckytool/assets/46134036/8f7ff5c1-60d1-4874-bd1b-1dc761a9a12d)

**Comment by luckyzyx** [comment]
This feature will be added in v1.2.1
