### ISSUE TITLE
开源协议道德绑架

### ISSUE THREAD

**Issue by Enmmma** [Xposed-Modules-Repo/com.luckyzyx.luckytool#12]
根据gpl-3.0协议，有人发现该项目未遵循协议，并向开发者提出，然而开发者却对开源协议表示十分轻蔑，具体可见https://www.coolapk.com/feed/53664920 ，然后在1.1.9版本的时候，取消了引用源代码入口，但并未删除其引用的代码，因此呼吁大家抵制这个模块，抵制不遵守开源协议的行为

**Comment by luckyzyx** [comment]
又是一个抱着开源名头道德绑架别人的傻逼

把别人的项目链接放在模块里是因为功能灵感启发而表达尊敬的，你怎么知道我都没有自己重写，恰恰就是你们这种人很多开发者才选择闭源

**Comment by Qingbuild** [comment]
这个作者说这是道德绑架，那你去直接去网上卖它这个模块，等他找你的时候你就说不要道德绑架，我就卖，不服你就去告我，笑死，既然他不想遵守规则，那你也别遵守，别和小偷讲道德

**Comment by luckyzyx** [comment]
> 这个作者说这是道德绑架，那你去直接去网上卖它这个模块，等他找你的时候你就说不要道德绑架，我就卖，不服你就去告我，笑死，既然他不想遵守规则，那你也别遵守，别和小偷讲道德

倒卖免费软件，真有你的，乐，

**Comment by Herobrine2005928** [comment]
乐
