### ISSUE TITLE
开源协议道德绑架第二期

### ISSUE THREAD

**Issue by Enmmma** [Xposed-Modules-Repo/com.luckyzyx.luckytool#13]
建议某开发者去好好学习一下什么是开源协议，遵循开源协议是开发者的义务，这是法律层面的问题，根本就不是道德问题，不遵守协议就是小偷行为，我都没去骂你，已经是我有素质了，你还有脸说什么道德绑架
还重（chao）写（xi）相关代码，哇，你很骄傲是不是？

**Comment by luckyzyx** [comment]
那你去告我啊，抓紧，我等着，LSP团队也不开源了，你也去告吧，真的搞笑

**Comment by Nimpip** [comment]
反正现在也停更了，好死
