### ISSUE TITLE
开源协议道德绑架第三期

### ISSUE THREAD

**Issue by Enmmma** [Xposed-Modules-Repo/com.luckyzyx.luckytool#15]
GPL协议生效的规定是应用为发布版本，Lsp是内部版，并不适用协议，你是发布版，你做贼就做贼，别指着别人给自己找借口，抄袭光荣，偷窃光荣，典型没三观的小学生。
哦，我提醒你一下，你可以锁话题，删issue，禁止我的账号在仓库上发言，可是我是不会闭嘴的

**Comment by luckyzyx** [comment]
你说得对，李某，少说那些没用的，来告我，求告，怎么就这点本事恶心我？也请继续在小绿书上征讨我，拉黑我干嘛，真的搞笑，屁都不敢放，就这点能耐么

**Comment by luckyzyx** [comment]
这几个issues都给你pin一下，我到要看看你还能整出什么乐子

**Comment by WindSakura** [comment]
不是哥们，你有啥实力谴责上人了，瞧你能的repo只要三个，一个pull都没有，issue提一大堆开源魔人🤣👉🤡

**Comment by luckyzyx** [comment]
那么请你这位认真阅读过开源协议的大牛说说看我这个微不足道的屎山模块开发者对开源环境造成了什么影响

我从来没有说过不开源是正确的行为，难道我就不希望过我的这个项目能好好开源发展下去？

既然没维护过项目，也不用别人的项目成果，那你凭什么站在第三方高高在上的角度批判开发者的行为，就凭你那高高在上的道德绑架精神？你以为你是谁啊

别的地方屁都不敢放一个，就敢在这个Github别人管不了的平台发布言论？

那么请多渠道多方面来征讨我，就搁这逼逼赖赖犯这个贱干嘛呢？到底是上没老下没小？还是整个户口本都没了？

就靠着我写的那丁点的开放源代码列表大放厥词，Xposed API的库写上去了代表着致敬意义，还有这几个项目的开发者都算得上我朋友，与其交流开发灵感后我写上去致敬有什么问题？

说再多对你这种开源魔人都没有意义，只会靠着已知的那点片面信息道德绑架，诸如之前所说重写＝抄袭，你又不是开发者你知道个勾八，网络上的键盘侠喷子应该都是师出于你

真要发扬你那道德绑架的开源精神的话就抓紧运用法律手段告我，没这个能耐就别逼逼赖赖，键盘侠当上瘾了是吧，你算个啥几把玩意啊

**Comment by luckyzyx** [comment]
所以你算个寄吧东西，我的项目想删啥就删啥，关你吊事

**Comment by luckyzyx** [comment]
所以你算个寄吧东西

**Comment by EasyAppleone** [comment]
你是不是脑子有问题了？不好好去工作来这耍大牌?这个人前口一句后口一句协议，协议个毛线

**Comment by EasyAppleone** [comment]
> 司马东西，到底是谁在装，自己心里有点逼数，你既然承认了违反协议做贼的事实，并且认为耍无赖就可以解决问题，那很好，等着，isuue别删

> 你是不是脑子有问题了？不好好去工作来这耍大牌?前口一句后口一句协议，协议个毛线，社区有你这种人才污染
