### ISSUE TITLE
Allow more than 5 apps to be locked

### ISSUE THREAD

**Issue by chaoscreater** [Xposed-Modules-Repo/com.luckyzyx.luckytool#25]
Hi,

In ColorOS, you can only lock a maximum of 5 apps. Is it possible for your tool to remove this restriction?

**Comment by luckyzyx** [comment]
This function already exists in LT module.

**Comment by chaoscreater** [comment]
> This function already exists in LT module.

Would you mind showing me where this setting is located? I went through every LT module setting and enabled a lot of them. Restarted my phone and the 5 apps lock limit is still there.
