### ISSUE TITLE
[BUG] GAMES modification doesnt work

### ISSUE THREAD

**Issue by wtfareu** [Xposed-Modules-Repo/com.luckyzyx.luckytool#29]
OnePlus GAMES modification doesnt work on oneplus 13 dor some reason please fix

**Comment by luckyzyx** [comment]
no log no fic

**Comment by wtfareu** [comment]
[LuckyTool_20240723_064417.log](https://github.com/user-attachments/files/16340391/LuckyTool_20240723_064417.log)
Here's the log man i hope you can see it, thanks.
