### ISSUE TITLE
[BUG] GAMES modification doesn't work

### ISSUE THREAD

**Issue by wtfareu** [Xposed-Modules-Repo/com.luckyzyx.luckytool#30]
OnePlus 13 GAMES modification/function doesnt work kindly see the log and if you can help me with this if this is device side issue or app issue, thanks.

[LuckyTool_20240723_064417.log](https://github.com/user-attachments/files/16340688/LuckyTool_20240723_064417.log)

**Comment by luckyzyx** [comment]
The module only adapts to the China version of the game assistant, and other versions cannot be repaired or adapted.

**Comment by luckyzyx** [comment]
The module only adapts to the China version of the game assistant, and other versions cannot be repaired or adapted.

**Comment by wtfareu** [comment]
> The module only adapts to the China version of the game assistant, and other versions cannot be repaired or adapted.
Is there a way that i can use it like install other game assistant app?
