### ISSUE TITLE
[BUG]Battery charge to 80% not working

### ISSUE THREAD

**Issue by agret** [Xposed-Modules-Repo/com.luckyzyx.luckytool#31]
![Screenshot_2024-07-30-10-09-40-05_a8e89bed8ceb754bee94ba00591e927a](https://github.com/user-attachments/assets/90873c54-415b-431a-adef-e0dd88e47d36)
![Screenshot_2024-07-30-10-05-59-51_0ba066473b79d6e213a1f6f52505e2ee~2](https://github.com/user-attachments/assets/25f3ca30-3037-4156-861e-1518c7546ffb)

**Comment by luckyzyx** [comment]
No valid information was provided, so it cannot be repaired.
