### ISSUE TITLE
[BUG反馈] 总会自动返回模块界面

### ISSUE THREAD

**Issue by mazemingw** [Xposed-Modules-Repo/com.luckyzyx.luckytool#4]
3.7版本，在QQ或者微信界面停留时，有几率会跳到luckytool界面，除此之外未见异常

**Comment by fonlan** [comment]
我是如果没有彻底杀掉LuckyTool的话每次手机解锁就会自动打开LuckyTool的界面，打开任务管理把LuckyTool划掉就不会出来了

**Comment by luckyzyx** [comment]
模块自启功能原理：屏幕解锁后调用模块触发强制刷新率和提升采样率功能

**Comment by luckyzyx** [comment]
已调整为无论前后台都会清理掉模块，再进行其他调用操作（当模块处于前台时，解锁后将被清理）

**Comment by luckyzyx** [comment]
已修复
