### ISSUE TITLE
[Feature Request] StatusBar Related functions request

### ISSUE THREAD

**Issue by Deleted-Account** [Xposed-Modules-Repo/com.luckyzyx.luckytool#7]
1. Double row clock text alignment:  
	Wish it could be aligned to left/right. (Current version is only center alignment)  

2. Double row clock position:  
	On my device (which has a left side digging screen), the clock is way so far away from the front camera.  
	Wish there could be a alignment setting.  

3. Double row clock date font:  
	I switch on month, date, week and double row. Switch off "Hide spaces".  
	But there is no space between week and date.  
	And the week font is a little bit bolder than date and clock.  
![810e195fd85ee12ff80d45f03e5d131](https://user-images.githubusercontent.com/48331538/216766055-7f93dab9-717c-4227-8b52-5d88ac678833.jpg)

4. Double row clock date/time format:  
	Wish it could be set to MMM dd or some other format. Then the date could be demonstrated like Thu Feb-02.  
	Or it could have more freedom of settings that we could type in date format as we wish.  
	(Like in Excel, 02/15/2023, date format set to ddd mmm-dd coule be shown like Wed Feb-15).  

5. NetWorkSpeed indicator:  
	Wish it could be invisible when there's no data exchange.  
	Wish the indicator could be set to the right position.  

6. StatusBar Battery Information:  
	It's a little bit annoying when switch on the "Battery information display".  
	There's always an indicator on statusbar and you cannot slide away the notification.  
	Wish there could be a setting that the indicator and notification could be shown only whilst charging.  
  
  
  
### Anyways, thanks alot for your great work.

**Comment by luckyzyx** [comment]
Issues related to the status bar have been basically addressed.

**Comment by Deleted-Account** [comment]
> Issues related to the status bar have been basically addressed.

So grateful for your update.


I set status bar clock mode to "Customize",
clock format set to
```
HH:mm:ss
EEE, MMM-dd
```
only while the font size set to 9.
the date could align to right buttons.

and the "EEE, MMM-" is bolder than other characters.
